apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    com.citusdata.role: Master
    kompose.cmd: ./kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: master
  name: master
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: master
    spec:
      containers:
      - image: tracyhenry/pg11_postgis25_citus811_plv8:latest
        name: citus-master
        args: ["postgres", "-c", "max_wal_size=50GB", "-c", "autovacuum_max_workers=3", "-c", "checkpoint_timeout=120min", "-c", "maintenance_work_mem=5GB"]
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
