apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    com.citusdata.role: Worker
    kompose.cmd: ./kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
      - image: tracyhenry/pg11_postgis25_citus811_plv8:latest
        name: worker
        args: ["postgres", "-c", "max_wal_size=50GB", "-c", "autovacuum_max_workers=2", "-c", "checkpoint_timeout=120min", "-c", "maintenance_work_mem=5GB"]
        resources: {}
      restartPolicy: Always
status: {}
